services:
  # Database PostgreSQL untuk project Rust
  database:
    image: postgres:alpine
    container_name: midman-rust-database
    restart: always
    environment:
      # Kamu bisa ganti value di bawah sesuai kebutuhan
      POSTGRES_USER: seira
      POSTGRES_PASSWORD: RootPassword123
      POSTGRES_DB: midman-db
    ports:
      - "5432:5432"
    volumes:
      - rust_pg_data:/var/lib/postgresql/data

volumes:
  rust_pg_data:
